### ISSUE TITLE
scarlet-nexus-dub pull failed

### ISSUE THREAD

**Issue by digitalw00t** [karl0ss/GoGoDownloader#3]
Was trying to pull the anime:  scarlet-nexus-dub
And I got the following.

Traceback (most recent call last):
  File "GoGoDownloader.py", line 164, in <module>
    gogodownloader(config)
  File "GoGoDownloader.py", line 153, in gogodownloader
    gogo.file_downloader(dl_links)
  File "/home/pulluser/GoGoDownloader/backend.py", line 150, in file_downloader
    dl.enqueue_file(
  File "/home/pulluser/.local/lib/python3.8/site-packages/parfive/downloader.py", line 216, in enqueue_file
    raise ValueError("URL must start with either 'http' or 'ftp'.")
ValueError: URL must start with either 'http' or 'ftp'.

**Comment by karl0ss** [comment]
Hey @digitalw00t 

Sometimes this happens if the CDN is down....can you try again? as I have just used without issue...

```
[>] Enter anime name > scarlet-nexus-dub
[>] Enter episode quality (1.SD/360P|2.SD/480P|3.HD/720P|4.FULLHD/1080P) > 4
[+] Title: Scarlet Nexus Dub
[+] Episode/s: 19
[+] Quality: 1080
[+] Link: https://gogoanime.film/category/scarlet-nexus-dub
[>] Do you want to download all episode? (y/n) > n
[>] Episode start > 1
[>] Episode end > 3
[+] Scraping Links
Files Downloaded:  33%|██████████████████████████████████████████████████████                                                                                                            | 1/3 [00:00<00:00,  2.48file/s]
(1920x1080-gogoanime)scarlet-nexus-dub-episode-1.mp4:   6%|███████▋                                                                                                                  | 16.9M/269M [00:21<02:48, 1.49MB/s]

```

**Comment by digitalw00t** [comment]
I did a pull, and there was a change.  After the pull now I get this.

[>] Enter anime name > scarlet-nexus-dub
[>] Enter episode quality (1.SD/360P|2.SD/480P|3.HD/720P|4.FULLHD/1080P) > 4
[+] Title: Scarlet Nexus Dub
[+] Episode/s: 20
[+] Quality: 1080
[+] Link: https://gogoanime.film/category/scarlet-nexus-dub
[>] Do you want to download all episode? (y/n) > n
[>] Episode start > 1
[>] Episode end > 20
[+] Scraping Links
1080 not found for ep1 checking for next best
1080 not found for ep2 checking for next best
1080 not found for ep3 checking for next best
1080 not found for ep4 checking for next best
1080 not found for ep5 checking for next best
1080 not found for ep6 checking for next best

**Comment by karl0ss** [comment]
Have you created and account on goganime, and added your username and password to the config file? It seems like it can't find the download links, they are only shown when your logged in..


Create config.json from config.json.default


Add your GoGoAnime Username and Password to config.json (Can't be a Google account)

**Comment by digitalw00t** [comment]
I have a valid username(email) and password in there.  It is a gmail.com email account though.  So you're saying I can't have a gmail account?

**Comment by karl0ss** [comment]
It would appear you can use a Google email, but it can't be an account that's "made via the Google link on their page" if that makes sense....it needs to use their own authentication method..

**Comment by digitalw00t** [comment]
Okay. So I made another account using protonmail.  Logged in with it, and same issue.

[>] Enter anime name > isekai-shokudou-2-dub
[>] Enter episode quality (1.SD/360P|2.SD/480P|3.HD/720P|4.FULLHD/1080P) > 4
[+] Title: Isekai Shokudou 2 Dub
[+] Episode/s: 10
[+] Quality: 1080
[+] Link: https://gogoanime.film/category/isekai-shokudou-2-dub
[>] Do you want to download all episode? (y/n) > y
[+] Scraping Links
1080 not found for ep1 checking for next best
1080 not found for ep2 checking for next best
1080 not found for ep3 checking for next best
1080 not found for ep4 checking for next best
1080 not found for ep5 checking for next best
1080 not found for ep6 checking for next best
1080 not found for ep7 checking for next best
1080 not found for ep8 checking for next best
1080 not found for ep9 checking for next best
1080 not found for ep10 checking for next best

**Comment by karl0ss** [comment]
Ok, I will have a go tomorrow...as I have only used it with my account, but I don't see any reason why it wouldn't work...

You are adding these details to the correct sections in the config.json file yeah?

**Comment by digitalw00t** [comment]
If you have a discord I could join, we can discuss this and maybe see what's at the bottom of this.  There are only two strings to add to the config file, so I can't honestly imagine what I might have wrong in there.

**Comment by karl0ss** [comment]
Just to confirm, you copied the config file `config.json.defualt` and renamed to `config.json`, and added your user/pass to the correct lines in that file?

I do not have discord, I will add a new version in the next day or so with some added loggin

**Comment by karl0ss** [comment]
Just to give you an example of my config.json
```
{
    "GoGoAnime_Username": "MyEmail@gmail.com",
    "GoGoAnime_Password": "MyGoGoPassword",
    "MaxConcurrentDownloads": 6,
    "CurrentGoGoAnimeDomain": "film",
    "OverwriteDownloads": 0
}
```

Please check its added as a string.

**Comment by digitalw00t** [comment]
Mine looks identical, save different username/password.  Are there any special characters in the password the script cannot handle?

**Comment by karl0ss** [comment]
I'm not tooo sure, my password doesn't have any special characters...

Really sorry about all this, not been at my laptop as not been well,but will be next week and will be able to have a proper look into it...

Could you try a password without special characters....

I will make a new build with added logging soon..

You are running form source I guess and not using the exe...what environment are you using? 

Thanks

**Comment by digitalw00t** [comment]
I'm running the source version from Linux Mint.

**Comment by karl0ss** [comment]
Ok, I still haven't found anything that woulds stop this working for you, and I already have checks in place for the config file, I will install this on my ubuntu wsl and see if it works ok there, as I have only tested it on windows so far..

**Comment by karl0ss** [comment]
I have just created a protonmail.com address to test this, and when signing up on GoGo with the address, I appear to have not recieved the email (over an hour of waiting), thus being unable to activate the account on GoGoAnime, did you manage to activate the account from GoGo anime? as if its not activated, then this will not work..

Can you login to gogo anime with the account you have created and have a look on an episode download page and see if you can see the download links.

Here I am not logged in, and the download links cannot be seen, this appears to be the state of the app for you at the moment
![download](https://user-images.githubusercontent.com/2493260/155171015-8a3540e4-8a3b-4a81-b600-21fce2b1d279.jpg)


Here I am logged in, and now the episode links are displayed.
![download](https://user-images.githubusercontent.com/2493260/155171150-9bdc3f8f-a64f-40aa-98db-ac36d827e4df.jpg)

**Comment by karl0ss** [comment]
I have just pushed 3.1.0 (only to source) this will blow up and tell you if it doens't believe you are logged in as it expects you to be when you try to download, as this will now check to see if the cookie got set when loggin in, if not, it will throw

```
[>] Enter anime name > one-piece
[>] Enter episode quality (1.SD/360P|2.SD/480P|3.HD/720P|4.FULLHD/1080P) > 4
[+] Title: One Piece
[+] Episode/s: 1011
[+] Quality: 1080
[+] Link: https://gogoanime.film/category/one-piece
[>] Do you want to download all episode? (y/n) > n
[>] Episode start > 1
[>] Episode end > 2
Traceback (most recent call last):
  File "f:\HomeCode\GoGoDownloader\GoGoDownloader.py", line 178, in <module>
    gogodownloader(config)
  File "f:\HomeCode\GoGoDownloader\GoGoDownloader.py", line 143, in gogodownloader
    gogo.user_logged_in_check()
  File "f:\HomeCode\GoGoDownloader\backend.py", line 131, in user_logged_in_check
    "User is not logged in, make sure account has been activated"
Exception: User is not logged in, make sure account has been activated
```

also, I still haven't recieved the activation email from gogo to prontomail, so i think maybe the issue if your account isn't activated on GoGoAnime?

Thanks

**Comment by digitalw00t** [comment]
Two things:
1:   After updating I got this on initial launch.
/home/falgout/git/GoGoDownloader/backend.py:129: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(loginCheck) is 0:
sh: 1: cls: not found

2:  It is ineed the activation issue.  At least now there is an error for it to be detected. :)  Let me see what I can do about that part as well.

**Comment by digitalw00t** [comment]
Okay.. the odd part is I can log into the web page with my credentials, and it shows me as logged in through the browser.  So why is the downloader saying that I'm not authenticated?

**Comment by karl0ss** [comment]
Morning,

Try the latest, I think you running an older python version, I have updated it to work with older version now and fixed the "cls not found issue"

**Comment by digitalw00t** [comment]
Still no go.  I'm running this version of python btw.
Python 3.8.10
pip3  list|grep -i soup
beautifulsoup4         4.10.0              
soupsieve              2.3.1

**Comment by karl0ss** [comment]
So what happens? does it kick back at you saying your not logged in? 

As you should not be getting the same issues as you did this morning as i have changed the code

> Two things: 1: After updating I got this on initial launch. /home/falgout/git/GoGoDownloader/backend.py:129: SyntaxWarning: "is" with a literal. Did you mean "=="? if len(loginCheck) is 0: sh: 1: cls: not found
> 
> 2: It is ineed the activation issue. At least now there is an error for it to be detected. :) Let me see what I can do about that part as well.

**Comment by digitalw00t** [comment]
"Exception: User is not logged in, make sure account has been activated"
Yet I can log into the site with my creds and watch anime from there showing that I'm logged in.  If I can't use protonmail or gmail for my account there, what are they expecting I wonder?

**Comment by karl0ss** [comment]
Interesting...I mean, I use a Gmail account, but not 'via their Gmail logon'

I setup a discord server

https://discord.gg/QSnw6G5Jss

Maybe you can join that and send me a DM with the username/pass that works for you on GoGoAnime so I can debug it?

**Comment by karl0ss** [comment]
Issue was due to invalid account
